### ISSUE TITLE
Docker-compose: container execution order

### ISSUE THREAD

**Issue by groom2hub** [tukcomCD2024/KbyC#39]
server가 DB보다 먼저 생성되어 DB 생성 전에 접근하려하여 오류 발생

**Comment by groom2hub** [comment]
다음 명렁어로 실행 순서 지정 가능
```
depends_on:
   - 먼저 실행할 이미지
```

**Comment by groom2hub** [comment]
DB 이미지가 실행 후 server 실행한다 해도 중간의 시간이 너무 짧음
> DB 정상적으로 실행될 때까지 대기, health check 후  server 실행
```
server:
  ...
  depends_on:
    database:
      condition: service_healthy  # 데이터베이스가 정상적으로 실행될 때까지 대기
   
  database:
    ...
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}"]  # 데이터베이스 헬스체크
```
